let dataUsuario = [
  {
    id: "userCity1",
    name: "Ignacio",
    lastName: "Borraz",
    age: 32,
    email: "ignacioborraz@hotmail.com",
    password: "Hola1234",
    code: "lee1234",
    verified: true,
    logged: true,
  },
  {
    id: "userCity2",
    name: "Ramiro",
    lastName: "Rojas",
    age: 20,
    email: "rami02@gmail.com",
    password: "rami02",
    code: "lee2002",
    verified: true,
    logged: true,
  },
  {
    id: "userCity3",
    name: "Ignacio",
    lastName: "Borraz",
    age: 32,
    email: "ignacioborraz@hotmail.com",
    password: "Hola1234",
    code: "lee1234",
    verified: true,
    logged: true,
  },
  {
    id: "userCity4",
    name: "Jovanny",
    lastName: "Vazquez",
    age: 30,
    email: "jovanyvazquez@gmail.com",
    password: "Mango",
    code: "mango1234",
    verified: true,
    logged: true,
  },
];
export default dataUsuario